/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3d/CoffeeMug.glb -o src/components/r3f/CoffeeMugModel.tsx --types --exportdefault --transform 
Files: CoffeeMug.glb [346.61KB] > CoffeeMug-transformed.glb [288.88KB] (17%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import modelUrl from '@/assets/3d/CoffeeMug-transformed.glb?url';

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
  };
  materials: {
    MugMaterial: THREE.MeshStandardMaterial;
    CoffeeMaterial: THREE.MeshStandardMaterial;
  };
  animations: Array<THREE.AnimationClip>;
};

export default function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh.geometry} material={materials.MugMaterial} />
      <mesh geometry={nodes.Mesh_1.geometry} material={materials.CoffeeMaterial} />
    </group>
  );
}

useGLTF.preload(modelUrl);
