/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesResponsive3dElementsRouteImport } from './routes/examples/responsive-3d-elements'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesResponsive3dElementsRoute =
  ExamplesResponsive3dElementsRouteImport.update({
    id: '/examples/responsive-3d-elements',
    path: '/examples/responsive-3d-elements',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/responsive-3d-elements': typeof ExamplesResponsive3dElementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/responsive-3d-elements': typeof ExamplesResponsive3dElementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples/responsive-3d-elements': typeof ExamplesResponsive3dElementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examples/responsive-3d-elements'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examples/responsive-3d-elements'
  id: '__root__' | '/' | '/examples/responsive-3d-elements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesResponsive3dElementsRoute: typeof ExamplesResponsive3dElementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/responsive-3d-elements': {
      id: '/examples/responsive-3d-elements'
      path: '/examples/responsive-3d-elements'
      fullPath: '/examples/responsive-3d-elements'
      preLoaderRoute: typeof ExamplesResponsive3dElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesResponsive3dElementsRoute: ExamplesResponsive3dElementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
